spring:
  application:
    name: student-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5010/student_db
    password: password
    username: postgres